language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm run install:ci
script:
  - npm run test:ci
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: build
  on:
    branch: master

